#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 21, 2017 11:36:57 AM
import sys
import dashboard
import Configurations
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import Login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = IPCS (root)
    Login_support.init(root, top)
    root.mainloop()

w = None
def create_IPCS(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = IPCS (w)
    Login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_IPCS():
    global w
    w.destroy()
    w = None


class IPCS:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("504x253+497+247")
        top.title("IPCS")
        top.configure(background="#ffffff")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.15, rely=0.2, height=21, width=350)
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''- Intelligent Pedestrian Controlling Crossing System -''')

        self.txtusername = Entry(top)
        self.txtusername.place(relx=0.42, rely=0.43, relheight=0.08
                , relwidth=0.33)
        self.txtusername.configure(background="white")
        self.txtusername.configure(disabledforeground="#a3a3a3")
        self.txtusername.configure(font="TkFixedFont")
        self.txtusername.configure(foreground="#000000")
        self.txtusername.configure(insertbackground="black")

        self.txtpwd = Entry(top)
        self.txtpwd.place(relx=0.42, rely=0.55, relheight=0.08, relwidth=0.33)
        self.txtpwd.configure(background="white")
        self.txtpwd.configure(disabledforeground="#a3a3a3")
        self.txtpwd.configure(font="TkFixedFont")
        self.txtpwd.configure(foreground="#000000")
        self.txtpwd.configure(insertbackground="black")

        self.Label2 = Label(top)
        self.Label2.place(relx=0.21, rely=0.43, height=21, width=70)
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Username''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.21, rely=0.55, height=21, width=70)
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Password''')

        self.lblError = Label(top)
        self.lblError.place(relx=0.24, rely=0.83, height=21, width=300)
        self.lblError.configure(background="#ffffff")
        self.lblError.configure(disabledforeground="#a3a3a3")
        self.lblError.configure(foreground="#c60d1b")
        

        def Login():
            username = self.txtusername.get() #user input username
            pwd = self.txtpwd.get() #user input password
            
            config = Configurations.Configuration()

            if((username == None) and (pwd == None)):
                self.lblError.configure(text='''Insert Login Details!''')
            
            if((config.getUserName() == username) and (config.getPassword() == pwd)):
                root.destroy()
                dashboard.vp_start_gui()

            else:
                self.lblError.configure(text='''Incorrect Login Details!''')
                print "Incorrect Login Details!"

        self.lblLogin = Button(top)
        self.lblLogin.place(relx=0.63, rely=0.71, height=24, width=58)
        self.lblLogin.configure(activebackground="#d9d9d9")
        self.lblLogin.configure(activeforeground="#000000")
        self.lblLogin.configure(background="#c5edc6")
        self.lblLogin.configure(command=Login_support.Login)
        self.lblLogin.configure(disabledforeground="#a3a3a3")
        self.lblLogin.configure(foreground="#000000")
        self.lblLogin.configure(highlightbackground="#d9d9d9")
        self.lblLogin.configure(highlightcolor="black")
        self.lblLogin.configure(pady="0")
        self.lblLogin.configure(text='''Login''', command=Login)
        self.lblLogin.configure(width=51)

      






if __name__ == '__main__':
    vp_start_gui()



